// This file is part of https://github.com/PalamaraLab/DataModule which is released under the GPL-3.0 license.
// See accompanying LICENSE and COPYING for copyright notice and full details.

#include "BedMatrixType.hpp"

#include <catch2/catch.hpp>

#include <cstdint>
#include <string>

#include <fmt/core.h>
#include <fmt/ranges.h>
#include <fmt/ostream.h>

namespace asmc {

TEST_CASE("BedMatrixType: test (small) real example", "[BedMatrixType]") {

  // Simulated data generated by plink, with fraction 0.05 missing data, 50 individuals, 100 SNPs
  std::string bedFile = DATA_MODULE_TEST_DIR "/data/bedbimfam/real_example.bed";
  std::string bimFile = DATA_MODULE_TEST_DIR "/data/bedbimfam/real_example.bim";
  std::string famFile = DATA_MODULE_TEST_DIR "/data/bedbimfam/real_example.fam";

  auto bedMatrix = BedMatrixType::createFromBedBimFam(bedFile, bimFile, famFile);

  CHECK(bedMatrix.getNumSites() == 100ul);
  CHECK(bedMatrix.getNumIndividuals() == 50ul);
}

} // namespace asmc
