name: Python 3.6-3.9 on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Install Python bindings
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - name: checkout repo & submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-${{ hashFiles('scripts/vcpkg_dependencies', 'vcpkg/CHANGELOG.md') }}

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: install python bindings
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .[dev] -v
        env:
          CXX: g++-9

      - name: python unit tests
        run: |
          pytest test/python
