name: Static analysis checks

on:
  push:
    branches:
      - xmain
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Static analysis checks
    runs-on: ubuntu-20.04

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-${{ hashFiles('scripts/vcpkg_dependencies', 'vcpkg/CHANGELOG.md') }}

      - name: install dependencies
        run: |
          bash scripts/install_dependencies.sh
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install analysers
        run: sudo apt install cppcheck clang-tidy-10

      - name: make build directories
        run: |
          mkdir cppcheck_dir
          mkdir clang_tidy_dir

      - name: compile with cppcheck
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CPPCHECK=ON
          cmake --build . --parallel 2 --target data_module_lib
        working-directory: cppcheck_dir
        env:
          CXX: clang++-10

      - name: compile with clang tidy
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_CLANG_TIDY=ON
          cmake --build . --parallel 2 --target data_module_lib
        working-directory: clang_tidy_dir
        env:
          CXX: clang++-10
